blank_issues_enabled: false
contact_links:
  - name: 'Official Help / Support for the parent repository'
    url: 'https://discord.gg/3NxYnyV?utm_source=Github'
    about: If you have support question or need help, please use their Discord Server.
